### PR TITLE
Change store_path() to not clear on-disk file if serialization fails

### LINKED ISSUE #47: Doesn't atomically save to file, resulting in possible file truncation or corruption
I've noticed that when confy tries to write to a file path, it overwrites the file in-place:

https://github.com/rust-cli/confy/blob/cd6932214ec16d50aa0f0defeb847a2e12618e61/src/lib.rs#L281-L287

In my experience (though not with apps using confy), overwriting files in-place causes problems. One possible issue (for files shared between many apps) is that either other applications will be able to read half-written contents, or the file will be locked and unreadable for the duration of the write. A more serious integrity issue is that if the application terminates during the file write (either from panicking, or from being terminated in taskmgr or Ctrl-C'd), it will result in a corrupted file being written to disk, with both the old and new file data being lost.

As an example of what can go wrong, a Python app I wrote (corrscope) saves config files directly to disk (since I didn't know better at the time), overwriting the previous file. Every few months I get a report from a user who can't open the app because the config file is corrupt and fails to load.

## What causes saving to fail?

Confy's `store_path()` first opens the file, then calls either `toml::to_string_pretty` or `serde_yaml::to_string` (both of which are fallible and return `Result<...>`), and use the `?` operator on the `Result`. If the function called fails, then `store_path()` exits, but the file on the disk has already been truncated and the damage is done. (I'm not sure if TOML or YAML serialization is likely to fail, either reliably or on edge cases, in unfinished programs on developer machines or in released applications on user machines.)

In corrscope, I suspect a similar event can occur if the serializer is left in a corrupted state. (I use a persistent global YAML serializer object for both documents and settings, since I hadn't learned Rust at the time, which would've taught me to avoid shared mutability.)

On top of this, there's the risk of getting terminated or Ctrl-C'd during the serialization operation (or if the serialization hangs and the app needs to be killed). I'm not sure if a system crash *after* the app finishes writing can lead to corruption, in various filesystems and journaling modes.

## Solutions

A common strategy is to write to a temporary file and rename it on top of the original. While imperfect (may not always preserve permissions or owners), it's the least bad strategy I'm aware of for saving generic textual config files. (An alternative, [advocated by danluu](https://danluu.com/file-consistency/), is to not rename on top of the original file, but use an external log file for crash recovery. However, this introduces complexity in the app, and is unworkable if other apps expect plaintext config files and don't understand how to recover from log files.)

Additionally if you want to recover from system crashes as well, you need to fsync the temporary file before renaming it to the original filename. If you don't do so, it's possible that the temporary file gets renamed and overwrites the original file (and the rename gets flushed to disk), but the system crashes before the temporary file's contents are written to disk.

Yet another level of protection is fsyncing the directory to ensure that if the system crashes after renaming the temporary file over the old file, the rename can't be reverted. However this is slower than not fsyncing the directory, is not necessary to prevent corruption on Linux, and is not possible on Windows.

https://github.com/untitaker/rust-atomicwrites is a crate that performs atomic file writing. However it performs a directory fsync on Linux, which I think is unnecessary, slow, and inconsistent between platforms. I would rewrite or vendor the crate without performing a directory fsync.

### PR DESCRIPTION
**Pull request by nyanpasu64**
Partly resolves #47.

I think this would benefit from a unit test to ensure that a failed serialization doesn't overwrite the file.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -296,6 +289,13 @@ pub fn store_path<T: Serialize>(path: impl AsRef<Path>, cfg: T) -> Result<(), Co
         s = serde_yaml::to_string(&cfg).map_err(ConfyError::SerializeYamlError)?;
     }
 
+    let mut f = OpenOptions::new()
+        .write(true)
+        .create(true)
+        .truncate(true)
+        .open(path)
+        .map_err(ConfyError::OpenConfigurationFileError)?;
+
```
Comment (matthiasbeyer) [inline src/lib.rs:298]: Why not chaining further?

```rust
    ...
    .open(path)
    .map_err(ConfyError::OpenConfigurationFileError)?
    .write_all(s.as_bytes())
    .map(|_| ())
    .map_err(ConfyError::WriteConfigurationFileError)
}
```

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]

File: src/lib.rs (hunk 1 above)
Comment (nyanpasu64) [reply src/lib.rs:298]: I'm occupied in other code right now, but personally I don't like deep method chaining.

In the original code, `OpenOptions::new()` acts as "open options", and `open()` turns it into a file. If I chain the file write as well, then `write_all()` turns it into a byte count written, and `.map(|_| ())` discards the byte count written. I feel that's too many things to keep track of in one expression.

When I have the time and energy, I might try it out, assemble the whole method chain together and then see how I like it.

Comment (nyanpasu64) [reply src/lib.rs:298]: Should I use:

```rs
    f.write_all(s.as_bytes())
        .map_err(ConfyError::WriteConfigurationFileError)?;
    Ok(())
```

or:

```rs
    f.write_all(s.as_bytes())
        .map_err(ConfyError::WriteConfigurationFileError)
```

**Comment by nyanpasu64** [comment]
I added a unit test ensuring that if you call `store_path()` with an object that fails to serialize, the file on disk will not be overwritten or truncated. I added the tempfile dev-dependency. Is this acceptable, or should I hard-code a path under `std::env::temp_dir()`?

File: src/lib.rs [hunk 2]
```diff
@@ -331,3 +331,67 @@ fn get_configuration_directory_str(project: &ProjectDirs) -> Result<&str, ConfyE
...
+            let mut buf = vec![];
+
+            use std::io::Read;
+            f.read_to_end(&mut buf)
+                .map_err(ConfyError::ReadConfigurationFileError)?;
+            buf
+        };
+
+        assert!(buf == message);
```
Comment (matthiasbeyer) [inline src/lib.rs:394]: Please use `assert_eq!()` here.

**Review by matthiasbeyer — CHANGES_REQUESTED** [review]
Besides this one small remark, I like the changeset here! :tada:

File: src/lib.rs (hunk 2 above)
Comment (nyanpasu64) [reply src/lib.rs]: Fixed. If I revert my bugfix commit but keep the test, the failing test prints:

```
thread 'tests::test_store_path' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 33]`', src/lib.rs:394:9
```

instead of a nice string. Is this an issue or not?

Comment (matthiasbeyer) [reply src/lib.rs]: I guess you can improve on this by using `assert_eq!(buf, message, "{} != {}", buf.to_string(), message.to_string());` or something like that. Feel free to push this improvement as individual commit! :smile:

Comment (nyanpasu64) [reply src/lib.rs]: So assert_eq!() has a format string for a custom failure message? Unfortunately you can't call `to_string` on `Vec<u8>` or `&[u8]`, and the workarounds at [Stack Overflow](https://stackoverflow.com/questions/19076719) are rather verbose for an error message that we never actually encounter.

I feel the more reasonable choices are converting `message` and `buf` into `String` and calling `f.read_to_string()` which errors if the file isn't UTF-8, or leaving the code as-is. (TBH I think we're spending far too long bikeshedding 🙁)

Comment (matthiasbeyer) [reply src/lib.rs]: Formatting that error message properly is mildly important, because if it fails you don't want to start converting bytes into a string in your head (some people might be able to do this, I am not). If you can make the error message nice with medium effort, go for it! :smile: If it is a major hassle, we can leave it as it is right now.

>  I think we're spending far too long bikeshedding

Meh, ... it doesn't block some serious deadline, so I don't mind. But if you think it's too much, I can go ahead and review + merge if you want me to (without any further changes to the assert case and if my review succeeds :smile: )!

Comment (nyanpasu64) [reply src/lib.rs]: Force-pushed the branch again, the error looks better now:

```
thread 'tests::test_store_path' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"Hello world!"`', src/lib.rs:394:9
```

Comment (matthiasbeyer) [reply src/lib.rs]: AFAIK there's no other CI.

**Comment by nyanpasu64** [comment]
The review still says it's waiting for changes even though I resolved the conversation. Should this be merged or edited or not?

**Review by matthiasbeyer — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
:tada: thanks for your contribution! :smile:
